Controllers/Admin/AdminController.cs
using System.Diagnostics;
using lovina_store.Data;
using lovina_store.Data.Interfaces;
using lovina_store.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace lovina_store.Controllers
{
    public class AdminController : Controller
    {

        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public AdminController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index()
        {
            if(HttpContext.Session.GetInt32("LoggedIn")==1){
                return View();
            } else {
                return RedirectToAction("Login");
            }
        }

        public IActionResult Login(){
            return View();
        }

        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            if(username == "root" && password == "root"){
                HttpContext.Session.SetInt32("LoggedIn", 1);
                return RedirectToAction("Index");
            } else {
                return View();
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("LoggedIn");
            return RedirectToRoute("default",
            new { controller = "Store", action = "Index" });
        }

    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="~/css/materialize.min.css" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="~/css/admin-style.css" />

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
    <div class="row">
        <ul id="sidenavbar" class="sidenav sidenav-fixed with-header col l2">
            <a asp-controller="Admin" asp-action="Index"><div id="logo">
                <img class="responsive-img" src="~/images/logo.png">
            </div></a>
            <li class="collection-header" ><h4>Produk</h4></li>
            <li class="collection-item"><a class="waves-effect waves-light" asp-controller="Admin" asp-action="Product">Kelola Produk</a></li>
            <li class="collection-item"><a class="waves-effect waves-light" asp-route="AdminProduct" asp-route-action="Create">Tambah Produk</a></li>
            <li class="collection-header"><h4>Kategori</h4></li>
            <li class="collection-item"><a class="waves-effect waves-light" asp-controller="Admin" asp-action="Category">Kelola Kategori</a></li>
            <li class="collection-item"><a class="waves-effect waves-light" asp-route="AdminCategory" asp-route-action="Create">Tambah Kategori</a></li>
            <li class="collection-header"><h4>Kontak</h4></li>
            <li class="collection-item"><a class="waves-effect waves-light" asp-controller="Admin" asp-action="Contact">Kelola Kontak</a></li>
            <li class="collection-header"><h4>Admin</h4></li>
            <li class="collection-item"><a class="waves-effect waves-light" asp-controller="Admin" asp-action="Logout">Logout</a></li>
        </ul>
    <a id="navbarbutton" href="#" data-target="sidenavbar" class="sidenav-trigger show-on-medium-and-down hide-on-large-only"><i class="material-icons medium">menu</i></a>
    <div id="content-wrapper" class="col s12 m12 offset-l2 l10">
    @RenderBody()
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/materialize/materialize.min.js"></script>
        <script src="~/js/admin.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script rc="~/lib/materialize/materialize.min.js"></script>
        <script src="~/js/admin.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LandingPageScript.cshtml
<script type="text/javascript" src="~/js/landing-page.js"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lovina Store</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @RenderBody()
</body>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</html>

Views/Shared/_StoreLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="~/css/materialize.min.css" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="~/css/fonts.css" />
    <link type="text/css" rel="stylesheet" href="~/css/store-style.css" />

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
    <div id="navbar-fixed">
        <div id="logo"><img src="~/images/logo.png" height="80px"></div>
        <form asp-controller="store" asp-action="catalog" autocomplete="off" id="search-bar" method="get">
            <div id="links" class="valign-wrapper">
                <input type="search" id="search-bar" name="keyword">
                <button class="btn waves-effect waves-light pink lighten-3" type="submit" name="action" style="margin-left: 10px;">Search
                    <i class="material-icons right">search</i>
                </button>
            </div>
        </form>
        <div style="clear: both;"></div>
    </div>
    
@RenderBody()

    <div id="footer-block">
        <div id="footer">
            <h2><span style="color: #f48fb1;">Lovina</span> Store</h2>
            <p>
                Pangalengan alamat jl rt rw toko bla bla bla
            </p>
            <p>
                Website by <a href="https://www.facebook.com/marlocoorawa" style="color: #f48fb1;">marlowololo</a>
            </p>
        </div>
    </div>

</body>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/materialize/materialize.min.js"></script>
    <script src="~/js/admin.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
</environment>
<script type="text/javascript" src="~/js/store.js"></script>

@RenderSection("Scripts", required: false)

</html>

Views/Shared/_StoreProductScript.cshtml
<script type="text/javascript" src="~/js/catalog.js"></script>